name: CI/CD Pipeline

on:
  push:
    branches:
      - ci-cd
  pull_request:
    branches:
      - ci-cd

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # Change to your required Node.js version

      - name: Install dependencies
        run: npm install  # Change this if you use another package manager

      - name: Run tests
        run: npm test  # Adjust this command as needed

      - name: Build
        run: npm run build  # Change this to your build command

      - name: Deploy
        run: echo "Deploy step goes here"  # Add your deployment command


